aws:
  s3:
    credentials:
      # Please ask for correct file
      #      path: src/main/resources/credentials/aws/.yml
      #      endpointUrl: https://s3.eu-central-1.amazonaws.com
      region: eu-central-1
      bucket: imagestoredev/users/
      accessKey: AKIARB2UKB5IDMXUHV76
      secretKey: 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
