spring:
  profiles:
    active: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: itripper0@gmail.com
    password: zozich2019
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

application:
  map:
    xmlsource: src/main/resources/maps/map.xml
    xmlsourcesavetodbqty: 10


amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: XXXXXXXXXXXXXXXXX
  secretKey: XXXXXXXXXXXXXXXXXXXXXXXXXX
  bucketName: your-bucket-name


---

spring:
  profiles: local

  datasource:
    url: jdbc:h2:mem:final-project-preparation
    username: root
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /console

server:
  port: 9000

aws:
  s3:
    credentials:
      path:
        src/main/resources/aws/s3/credentials/dev

---

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://danit.cukm9c6zpjo8.us-west-2.rds.amazonaws.com:3306/fs5
    username: fs5_user
    password: bArceloNa
    data: classpath*:data.sql

  jpa:
    hibernate:
      ddl-auto: create

aws:
  s3:
    credentials:
      path:
        src/main/resources/aws/s3/credentials/dev

---

spring:
  profiles: prod

aws:
  s3:
    credentials:
      path:
        src/main/resources/aws/s3/credentials/prod