spring:
  profiles:
    active: local

    include: S3dev

mail:
    host: smtp.gmail.com
    port: 587
    username: itripper0@gmail.com
    password: zozich2019
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

application:
  map:
    xmlsource: src/main/resources/maps/map.xml
    xmlsourcesavetodbqty: 10
  images:
    save: AWSS3

  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect




---

spring:
  profiles: local

  datasource:
    url: jdbc:h2:mem:final-project-preparation
    username: root
    password:
    driver-class-name: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <GOOGLE_CLIENT_ID>
            clientSecret: <GOOGLE_CLIENT_SECRET>
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: <FACEBOOK_CLIENT_ID>
            clientSecret: <FACEBOOK_CLIENT_SECRET>
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: <GITHUB_CLIENT_ID>
            clientSecret: <GITHUB_CLIENT_SECRET>
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

  h2:
    console:
      enabled: true
      path: /console

server:
  port: 9000

---

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://danit.cukm9c6zpjo8.us-west-2.rds.amazonaws.com:3306/fs5
    username: fs5_user
    password: bArceloNa
    data: classpath*:data.sql

  jpa:
    hibernate:
      ddl-auto: create

---

spring:
  profiles: prod