spring:
  profiles:
    active: dev
  resources:
    static-locations: src/main/resources/static/
  mail:
    host: smtp.gmail.com
    port: 587
    username: itripper0@gmail.com
    password: zozich2019
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false
  servlet:
    multipart:
      max-file-size: 10MB
#      max-request-size: 10MB

application:
  map:
    xmlsource: src/main/resources/maps/map.xml
    xmlsourcesavetodbqty: 10
  images:
    save: AwsS3Db0,LocalDb
#    save: AwsS3Db0
#    save: LocalDb
  credentials:

    dev-awsdb:  src/main/resources/credentials/aws/dev-awsdb.properties
    prod-awsdb: src/main/resources/credentials/aws/db-prod.properties

---

spring:
  profiles: local

  datasource:
    url: jdbc:h2:mem:final-project-preparation
    username: root
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /console

server:
  port: 9000

aws:
  s3:
    credentials:
      path: src/main/resources/credentials/aws/credentials.properties
      endpointUrl: https://s3.eu-central-1.amazonaws.com
      bucketName: imagestoredev/users
      imageExtension: .png

---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

server:
  port: 9000

aws:
  s3:
    credentials:
      path: src/main/resources/credentials/aws/credentials.properties
      endpointUrl: https://s3.eu-central-1.amazonaws.com
      bucketName: imagestoredev/users
      imageExtension: .png


---

spring:
  profiles: prod

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://pickupprd.c3fhdfnyqb9c.eu-central-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password:

aws:
  s3:
    credentials:
      path:
        src/main/resources/aws/s3/credentials/prod