server:
  port: 9000

spring:
  profiles:
    active: local

  mail:
    host: smtp.gmail.com
    port: 587
    username: <itripper0@gmail.com>
    password: <zozich2019>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

spring:
  profiles: local

  datasource:
    url: jdbc:h2:mem:final-project-preparation
    username: root
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /console

---

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://danit.cukm9c6zpjo8.us-west-2.rds.amazonaws.com:3306/fs5
    username: fs5_user
    password: bArceloNa
    data: classpath*:data.sql

  jpa:
    hibernate:
      ddl-auto: create

---

spring:
  profiles: prod

