export const GET_TRIP_REQUEST = 'GET_TRIP_REQUEST'
export const GET_TRIP_SUCCESS = 'GET_TRIP_SUCCESS'
export const GET_TRIP_FAILED = 'GET_TRIP_FAILED'
// export const GET_USER_PHOTO = 'GET_USER_PHOTO'

export const USER_NAME = 'USER_NAME'
export const TRIP_DATE_TIME = 'TRIP_DATE_TIME'
export const TYPE = 'TYPE'
export const USER_PHOTO = 'USER_PHOTO'
export const FEEDBACK_TRIP_ID_WHO = 'FEEDBACK_TRIP_ID_WHO'
export const FEEDBACK_TRIP_ID_WHOM = 'FEEDBACK_TRIP_ID_WHOM'
export const TRIP_POINT_NAME_FROM = 'TRIP_POINT_NAME_FROM'
export const TRIP_POINT_NAME_TO = 'TRIP_POINT_NAME_TO'
export const FEEDBACK_VALUE = 'FEEDBACK_VALUE'
export const FEEDBACK_DRIVER_TRIP_ID = 'FEEDBACK_DRIVER_TRIP_ID'
export const FEEDBACK_PASSENGER_TRIP_ID = 'FEEDBACK_PASSENGER_TRIP_ID'
export const FEEDBACK_USER_WHO_ID = 'FEEDBACK_USER_WHO_ID'
export const FEEDBACK_USER_WHOM_ID = 'FEEDBACK_USER_WHOM_ID'
export const GET_USER_PHOTO = 'GET_USER_PHOTO'
export const NAME_FROM = 'NAME_FROM'
export const NAME_TO = 'NAME_TO'



