export const SET_AUTH = 'SET_AUTH'
export const SET_USER = 'SET_USER'
export const SET_CARS = 'SET_CARS'
export const SET_USER_POINTS = 'SET_USER_POINTS'
export const SET_COMMON_POINTS = 'SET_COMMON_POINTS'
export const SET_ROLE = 'SET_ROLE'
export const SET_SOCIAL_AUTH = 'SET_SOCIAL_AUTH'
export const MENU_TOGGLE = 'MENU_TOGGLE'
export const SET_CAR_LIST = 'SET_CAR_LIST'
export const LOGIN_REJECTED = 'LOGIN_REJECTED'
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_TRIP = 'SET_TRIP'
export const SET_MY_COORDS = 'SET_MY_COORDS'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
export const SET_PROFILE  = 'SET_PROFILE'
export const DELETE_TRIP_FROM_HISTORY  = 'DELETE_TRIP_FROM_HISTORY'
export const USER_LOGOUT  = 'USER_LOGOUT'
export const SET_SEARCHED_LOCATION  = 'SET_SEARCHED_LOCATION'
export const SET_TARGET_COORDS  = 'SET_TARGET_COORDS'
export const GET_LOCATION_REQUEST ='GET_LOCATION_REQUEST'
export const GET_LOCATION_SUCCESS ='GET_LOCATION_SUCCESS'
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR'
export const INITIAL_LOAD = 'INITIAL_LOAD'
export const SET_USER_PHOTO = 'SET_USER_PHOTO'
export const ADD_CAR = 'ADD_CAR'
export const SET_INTERMEDIATE_POINTS = 'SET_INTERMEDIATE_POINTS'

export const ADD_TRIP_DATE = 'ADD_TRIP_DATE'
export const ADD_NEW_TRIP = 'ADD_NEW_TRIP'
export const LIVE_SEARCH_SHOW = 'LIVE_SEARCH_SHOW'






